apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: n8r8qjxwz-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap-test-organization-jk/rhtap-qe:f2ae6ae0375c7fe7b2251cdce3c4f1977ad640c3@sha256:2bd4f6ffcf6117a2ea30860fc2a8cd8dea5c5da5c726a1c5dfe765ccaeeab2f2
          name: container-image
