apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: n8r8qjxwz-nodejs
  janus-idp.io/tekton: n8r8qjxwz-nodejs
  backstage.io/kubernetes-id: n8r8qjxwz-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: n8r8qjxwz-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
